import os, sys, json, hashlib, getpass
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
PRIVATE_DIR = ROOT / ".private"
PRIVATE_KEY_FILE = PRIVATE_DIR / "signing_private_key.pem"
SIGNING_MODULE = ROOT / "notmyfault" / "security" / "signing_keys.py"
PLUGIN_DIRS = [
    (Path("actions"), "action.json"),
    (Path("triggers"), "trigger.json"),
]

def _get_crypto():
    from cryptography.hazmat.primitives.asymmetric import ed25519
    from cryptography.hazmat.primitives.serialization import (
        load_ssh_private_key, load_ssh_public_key, Encoding, PrivateFormat, PublicFormat, NoEncryption, BestAvailableEncryption, load_pem_private_key
    )
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    return ed25519, load_ssh_private_key, load_ssh_public_key, Encoding, PrivateFormat, PublicFormat, NoEncryption, BestAvailableEncryption, load_pem_private_key, Ed25519PrivateKey


def _prompt_passphrase(prompt="请输入签名密码: ", confirm=False) -> str | None:
    env = os.environ.get("NOTMYFAULT_SIGNING_PASSPHRASE", "")
    if env:
        return env
    try:
        pw = getpass.getpass(prompt)
        if confirm and pw:
            pw2 = getpass.getpass("请再次输入确认: ")
            if pw != pw2:
                print("! 两次输入不一致")
                return None
        return pw
    except (EOFError, KeyboardInterrupt):
        print()
        return None


def _save_private_key(key, path: Path, encrypt: bool = False) -> None:
    """保存私钥并按参数决定是否加密"""
    _, _, _, Encoding, PrivateFormat, _, NoEncryption, BestAvailableEncryption, _, _ = _get_crypto()
    if encrypt:
        pw = _prompt_passphrase("设置签名密码: ", confirm=True)
        if pw is None:
            raise SystemExit(1)
        if not pw:
            print("! 密码不能为空")
            raise SystemExit(1)
        encryption = BestAvailableEncryption(pw.encode())
    else:
        encryption = NoEncryption()
    pem = key.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, encryption)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        f.write(pem)
    status = "已加密" if encrypt else "已保存"
    print(f"+ 私钥{status}: {path}")


try:
    from notmyfault.security.signing import load_private_key, sign_plugin, plugin_files, sign_file
except ImportError:
    print("! 无法导入签名模块，请确保项目结构完整", file=sys.stderr)
    raise SystemExit(1)

def _collect_plugins():
    """收集内置插件目录及其主 JSON 文件名"""
    plugins = []
    for dir_type, json_name in PLUGIN_DIRS:
        d = ROOT / "notmyfault" / dir_type
        if d.is_dir():
            for p in sorted(d.iterdir()):
                if p.is_dir() and p.name != "__pycache__":
                    jf = p / json_name
                    if jf.exists():
                        plugins.append((p, json_name))
    return plugins

# 签名、校验和内置加载使用同一份文件清单，合法签名才能得到一致结果

def cmd_init_keys(args):
    """生成 Ed25519 密钥对"""
    ed25519, _, _, Encoding, _, PublicFormat, *_ = _get_crypto()
    
    if PRIVATE_KEY_FILE.exists() and not args.get("force"):
        print("! 私钥已存在，跳过。使用 --force 覆盖")
        return
    
    private_key = ed25519.Ed25519PrivateKey.generate()
    _save_private_key(private_key, PRIVATE_KEY_FILE, encrypt=args.get("encrypt"))
    
    public_key = private_key.public_key()
    pub_bytes = public_key.public_bytes(Encoding.Raw, PublicFormat.Raw)
    
    # 公钥写入 .private 目录供当前开发者使用，该目录不纳入 git
    pub_file = PRIVATE_DIR / "signing_public.pem"
    with open(pub_file, "wb") as f:
        f.write(pub_bytes)
    print(f"+ 用户公钥: {pub_file}（不检入 git）")
    print(f"+ 公钥指纹: {hashlib.sha256(pub_bytes).hexdigest()[:16]}...")
    
    # 指定 --builtin 或缺少 signing_keys.py 时写入内置公钥
    if args.get("builtin") or not SIGNING_MODULE.exists() or SIGNING_MODULE.stat().st_size < 50:
        code = '"""NotmyFault plugin signing public keys.\nBUILTIN_PUBLIC_KEY — project maintainer\'s key, tracked in git.\nUSER_PUBLIC_KEY   — loaded from .private/signing_public.pem, not tracked.\nGenerated by build.py init-keys. DO NOT EDIT.\n"""\n'
        code += '\nimport os\nfrom typing import Optional\n\n'
        code += 'CURDIR = os.path.dirname(os.path.abspath(__file__))\n'
        code += '_PRIVATE_DIR = os.path.normpath(os.path.join(CURDIR, "..", "..", ".private"))\n\n'
        code += f'BUILTIN_PUBLIC_KEY: bytes = {pub_bytes!r}\n\n'
        code += '_USER_PUBLIC_KEY_PATH = os.path.join(_PRIVATE_DIR, "signing_public.pem")\n\n\n'
        code += 'def _load_user_public_key() -> Optional[bytes]:\n'
        code += '    try:\n'
        code += '        with open(_USER_PUBLIC_KEY_PATH, "rb") as f:\n'
        code += '            return f.read()\n'
        code += '    except (OSError, FileNotFoundError):\n'
        code += '        return None\n\n\n'
        code += 'USER_PUBLIC_KEY: Optional[bytes] = _load_user_public_key()\n\n\n'
        code += 'def get_public_keys() -> list[bytes]:\n'
        code += '    keys: list[bytes] = []\n'
        code += '    if BUILTIN_PUBLIC_KEY:\n'
        code += '        keys.append(BUILTIN_PUBLIC_KEY)\n'
        code += '    if USER_PUBLIC_KEY:\n'
        code += '        keys.append(USER_PUBLIC_KEY)\n'
        code += '    return keys\n'
        with open(SIGNING_MODULE, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"+ 内置公钥: {SIGNING_MODULE}（检入 git）")

def cmd_sign(args):
    """签名所有插件并返回供构建签名复用的私钥"""
    if not PRIVATE_KEY_FILE.exists():
        print("! 私钥不存在，请先运行 build.py init-keys")
        raise SystemExit(1)

    private_key = load_private_key(PRIVATE_KEY_FILE)
    plugins = _collect_plugins()
    signed = 0
    for plugin_dir, json_name in plugins:
        sign_plugin(plugin_dir, json_name, private_key)
        plugin_id = json.loads((plugin_dir / json_name).read_text(encoding="utf-8")).get("id", plugin_dir.name)
        print(f"  + {plugin_id:20s} signed ({len(plugin_files(plugin_dir))} files)")
        signed += 1
    print(f"已签名 {signed} 个插件")
    return private_key

def cmd_verify(args):
    ed25519, *_ = _get_crypto()
    
    try:
        from notmyfault.security.signing_keys import get_public_keys
        pub_keys = get_public_keys()
    except ImportError:
        print("! 无法导入公钥模块，请先运行 build.py init-keys")
        raise SystemExit(1)
    
    if not pub_keys:
        print("! 没有可用的公钥，请先运行 build.py init-keys")
        raise SystemExit(1)
    
    pubs = [ed25519.Ed25519PublicKey.from_public_bytes(k) for k in pub_keys]
    
    plugins = _collect_plugins()
    passed = 0
    failed = 0
    unsigned = 0
    for plugin_dir, json_name in plugins:
        sig_file = plugin_dir / "signature.sig"
        if not sig_file.exists():
            print(f"  - {plugin_dir.parent.name:10s}/{plugin_dir.name:20s} 未签名")
            unsigned += 1
            continue
        from notmyfault.security.signing import plugin_payload

        payload = plugin_payload(plugin_dir)
        digest = hashlib.sha256(payload).digest()
        sig = sig_file.read_bytes()
        ok = False
        for pk in pubs:
            try:
                pk.verify(sig, digest)
                ok = True
                break
            except Exception:
                continue
        if ok:
            plugin_id = json.loads((plugin_dir / json_name).read_text(encoding="utf-8")).get("id", plugin_dir.name)
            print(f"  + {plugin_id:20s} 签名有效")
            passed += 1
        else:
            print(f"  ! {plugin_dir.parent.name}/{plugin_dir.name:20s} 签名无效！")
            failed += 1
    print(f"验证完成: {passed} 有效, {failed} 无效, {unsigned} 未签名")
    # 非零退出码由 CI 和发布脚本识别无效或缺失签名
    if failed > 0 or unsigned > 0:
        raise SystemExit(1)

def _key_is_encrypted() -> bool:
    if not PRIVATE_KEY_FILE.exists():
        return False
    return b"ENCRYPTED" in PRIVATE_KEY_FILE.read_bytes()[:40]


def _ensure_strict_encrypted_key() -> None:
    """为 strict 模式准备密码加密的私钥，缺少时生成。"""
    if PRIVATE_KEY_FILE.exists() and _key_is_encrypted():
        return
    if not PRIVATE_KEY_FILE.exists():
        print("[strict] 未找到私钥；strict 模式需要密码加密的私钥，现在生成。")
        cmd_init_keys({"force": False, "builtin": True, "encrypt": True})
    else:
        print("[strict] 当前私钥未加密；strict 模式要求加密，现在为它设置密码。")
        key = load_private_key(PRIVATE_KEY_FILE)  # 未加密，无需密码即可加载
        _save_private_key(key, PRIVATE_KEY_FILE, encrypt=True)


def _ensure_key_for_build(security_mode: str, force: bool = False) -> None:
    """按安全模式准备签署 build.json 所需的私钥，strict 模式还要求私钥加密"""
    if security_mode == "strict":
        if force:
            print("[strict] --force：重新生成加密私钥（会要求设置密码）。")
            cmd_init_keys({"force": True, "builtin": True, "encrypt": True})
            return
        _ensure_strict_encrypted_key()
        return
    # normal 和 permissive 模式接受未加密私钥
    if force or not PRIVATE_KEY_FILE.exists():
        if force and PRIVATE_KEY_FILE.exists():
            print(f"[{security_mode}] --force：重新生成不加密私钥（覆盖现有私钥）。")
        else:
            print(f"[{security_mode}] 未找到私钥，生成一个（不加密）用于签名 build.json。")
        cmd_init_keys({"force": bool(force), "builtin": True, "encrypt": False})


def cmd_build(args):
    """签名插件并写入带签名的 build.json，默认使用 strict 模式"""
    security_mode = args.get("security_mode") or "strict"
    if security_mode not in ("strict", "normal", "permissive"):
        print(f"! 未知 security_mode: {security_mode}（应为 strict / normal / permissive）")
        raise SystemExit(1)

    # build.json 需要私钥签名，strict 模式还会强制加密
    _ensure_key_for_build(security_mode, force=args.get("force"))

    # cmd_sign 返回的私钥同时用于插件和 build.json，减少一次解锁
    private_key = cmd_sign(args)

    # 记录当前 Git 分支，安全模式只由命令行参数决定
    branch = "unknown"
    try:
        import subprocess
        r = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True, timeout=3)
        branch = r.stdout.strip()
    except Exception:
        pass

    build_info = {
        "security_mode": security_mode,
        "build": branch,
        "build_time": __import__("datetime").datetime.now().isoformat(),
    }
    build_path = ROOT / "build.json"
    with open(build_path, "w", encoding="utf-8") as f:
        json.dump(build_info, f, indent=2)

    # build.json 未签名时，引擎使用 strict 模式
    if private_key is not None:
        sign_file(build_path, private_key)
        print(f"+ build.json 签名: {build_path}.sig")
        # 生成核心源码哈希清单并签名
        _build_integrity_manifest(private_key)
    else:
        print("! 缺少私钥，build.json 未签名 -- 引擎将不信任它（回退 strict）。", file=sys.stderr)
    print(f"+ build.json 写入: {build_path} (mode={security_mode}, branch={branch})")


def _build_integrity_manifest(private_key) -> None:
    """生成核心 Python 文件的哈希清单并用 Ed25519 签名"""
    pkg_dir = ROOT / "notmyfault"
    files = {}
    # 清单覆盖根包和核心子包，跳过测试、模拟器、动作插件、触发器插件及缓存目录
    for p in sorted(pkg_dir.rglob("*.py")):
        rel = p.relative_to(pkg_dir).as_posix()
        parts = rel.split("/")
        if parts[0] in ("tests", "simulator", "actions", "__pycache__") or "__pycache__" in parts:
            continue
        if parts[0] == "triggers" and rel not in ("triggers/__init__.py", "triggers/base.py"):
            continue
        files[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    manifest_path = pkg_dir / "integrity.json"
    manifest_path.write_text(
        json.dumps({"files": files}, indent=2, sort_keys=True), encoding="utf-8"
    )
    sign_file(manifest_path, private_key)
    print(f"+ 完整性清单: {manifest_path} + .sig ({len(files)} 个核心文件)")

def cmd_version(args):
    priv_ok = PRIVATE_KEY_FILE.exists()
    try:
        from notmyfault.security.signing_keys import BUILTIN_PUBLIC_KEY
        pub_ok = bool(BUILTIN_PUBLIC_KEY)
    except ImportError:
        pub_ok = False
    # Windows 控制台可能使用 GBK，状态输出使用 ASCII 符号
    print(f"私钥: {'OK' if priv_ok else 'MISSING'} {PRIVATE_KEY_FILE}")
    print(f"公钥: {'OK' if pub_ok else 'MISSING'} {SIGNING_MODULE}")
    if pub_ok:
        fp = hashlib.sha256(BUILTIN_PUBLIC_KEY).hexdigest()[:16]
        print(f"公钥指纹: {fp}...")
    plugins = _collect_plugins()
    sig_count = sum(1 for d, _ in plugins if (d / "signature.sig").exists())
    print(f"插件: {len(plugins)} 个, 已签名: {sig_count} 个")

def _print_usage(cmds):
    print("用法: python build.py <command> [options]")
    print(f"命令: {', '.join(sorted(cmds))}")
    print("选项: --force                  强制覆盖已有密钥（build 里：按当前模式重新生成私钥）")
    print("      --builtin                同时写入内置公钥到 signing_keys.py")
    print("      --encrypt                用密码加密私钥（init-keys 用）")
    print("      --security-mode=MODE     指定安全模式: strict / normal / permissive")
    print("                               （仅 build 命令；默认 strict）")
    print("说明: 直接 `python build.py`（不带子命令）= build。")
    print("      permissive/normal 用不加密私钥免密码；若现有私钥是加密的，加 --force 重新生成不加密私钥（覆盖现有）。")
    print("      fresh clone 必须先跑一次以生成插件签名与 build.json。")


def main():
    cmds = {
        "init-keys": cmd_init_keys,
        "sign": cmd_sign,
        "verify": cmd_verify,
        "build": cmd_build,
        "version": cmd_version,
        "help": lambda args: _print_usage(cmds),
    }
    # 从命令行读取安全模式，未指定时使用 strict
    security_mode = None
    for a in sys.argv:
        if a.startswith("--security-mode="):
            security_mode = a.split("=", 1)[1].strip().lower()
    args = {
        "force": "--force" in sys.argv,
        "builtin": "--builtin" in sys.argv,
        "encrypt": "--encrypt" in sys.argv,
        "security_mode": security_mode,
    }
    cmds_list = [a for a in sys.argv[1:] if not a.startswith("--")]

    if not cmds_list:
        # 未指定子命令时按安全模式执行默认 build
        mode = security_mode or "strict"
        extra = "，会要求设置签名密码" if mode == "strict" else "（permissive/normal 用不加密私钥，免密码；加 --force 可重新生成不加密私钥）"
        print(f"[build] 未指定子命令，默认执行 build（{mode}{extra}）。")
        print("[build] 查看完整用法: python build.py help")
        cmds_list = ["build"]

    for cmd_name in cmds_list:
        if cmd_name in cmds:
            cmds[cmd_name](args)
        else:
            print(f"未知命令: {cmd_name}")
            _print_usage(cmds)
            raise SystemExit(1)

if __name__ == "__main__":
    main()
