import os, sys, json, hashlib, getpass
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
PRIVATE_DIR = ROOT / ".private"
PRIVATE_KEY_FILE = PRIVATE_DIR / "signing_private_key.pem"
SIGNING_MODULE = ROOT / "notmyfault" / "signing_keys.py"
PLUGIN_DIRS = [("actions", "action.json"), ("triggers", "trigger.json")]

def _get_crypto():
    from cryptography.hazmat.primitives.asymmetric import ed25519
    from cryptography.hazmat.primitives.serialization import (
        load_ssh_private_key, load_ssh_public_key, Encoding, PrivateFormat, PublicFormat, NoEncryption, BestAvailableEncryption, load_pem_private_key
    )
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    return ed25519, load_ssh_private_key, load_ssh_public_key, Encoding, PrivateFormat, PublicFormat, NoEncryption, BestAvailableEncryption, load_pem_private_key, Ed25519PrivateKey


def _prompt_passphrase(prompt="请输入签名密码: ", confirm=False) -> str | None:
    env = os.environ.get("NOTMYFAULT_SIGNING_PASSPHRASE", "")
    if env:
        return env
    try:
        pw = getpass.getpass(prompt)
        if confirm and pw:
            pw2 = getpass.getpass("请再次输入确认: ")
            if pw != pw2:
                print("! 两次输入不一致")
                return None
        return pw
    except (EOFError, KeyboardInterrupt):
        print()
        return None


def _save_private_key(key, path: Path, encrypt: bool = False) -> None:
    """保存私钥（可选口令加密）。"""
    _, _, _, Encoding, PrivateFormat, _, NoEncryption, BestAvailableEncryption, _, _ = _get_crypto()
    if encrypt:
        pw = _prompt_passphrase("设置签名密码: ", confirm=True)
        if pw is None:
            raise SystemExit(1)
        if not pw:
            print("! 密码不能为空")
            raise SystemExit(1)
        encryption = BestAvailableEncryption(pw.encode())
    else:
        encryption = NoEncryption
    pem = key.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, encryption)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        f.write(pem)
    status = "已加密" if encrypt else "已保存"
    print(f"+ 私钥{status}: {path}")


def _load_private_key(path: Path):
    """加载私钥（自动识别加密/明文，兼容旧版 Raw 格式）。"""
    _, _, _, _, _, _, _, _, _, load_pem_private_key, Ed25519PrivateKey = _get_crypto()
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError:
        print(f"! 无法读取私钥文件: {path}")
        raise SystemExit(1)

    if data.startswith(b"-----BEGIN "):
        try:
            return load_pem_private_key(data, password=None)
        except Exception:
            pw = _prompt_passphrase()
            if pw is None:
                raise SystemExit(1)
            return load_pem_private_key(data, password=pw.encode())

    # 旧版 Raw 格式（明文，无加密）
    print("  检测到旧版明文私钥，将在下次 init-keys --force 时迁移")
    return Ed25519PrivateKey.from_private_bytes(data)

def _collect_plugins():
    """返回所有插件目录列表 [(plugin_dir, main_json_name), ...]"""
    plugins = []
    for dir_type, json_name in PLUGIN_DIRS:
        d = ROOT / "notmyfault" / dir_type
        if d.is_dir():
            for p in sorted(d.iterdir()):
                if p.is_dir() and p.name != "__pycache__":
                    jf = p / json_name
                    if jf.exists():
                        plugins.append((p, json_name))
    return plugins

def _plugin_files(plugin_dir, json_name):
    """返回插件目录中需要签名的文件列表（按文件名排序）"""
    allowed = {json_name, json_name.replace("action", "action").replace("trigger", "trigger")}
    files = []
    for f in sorted(plugin_dir.iterdir()):
        if f.is_file() and f.suffix in (".py", ".json") and f.name != "signature.sig":
            files.append(f)
    return files

def cmd_init_keys(args):
    """生成 Ed25519 密钥对"""
    ed25519, _, _, Encoding, _, PublicFormat, *_ = _get_crypto()
    
    if PRIVATE_KEY_FILE.exists() and not args.get("force"):
        print("! 私钥已存在，跳过。使用 --force 覆盖")
        return
    
    private_key = ed25519.Ed25519PrivateKey.generate()
    _save_private_key(private_key, PRIVATE_KEY_FILE, encrypt=args.get("encrypt"))
    
    public_key = private_key.public_key()
    pub_bytes = public_key.public_bytes(Encoding.Raw, PublicFormat.Raw)
    
    # 写入本地用户公钥文件（不检入 git，每个开发者可持有自己的密钥）
    pub_file = PRIVATE_DIR / "signing_public.pem"
    with open(pub_file, "wb") as f:
        f.write(pub_bytes)
    print(f"+ 用户公钥: {pub_file}（不检入 git）")
    print(f"+ 公钥指纹: {hashlib.sha256(pub_bytes).hexdigest()[:16]}...")
    
    # 仅在显式指定 --builtin 或 signing_keys.py 不存在时写入内置公钥
    if args.get("builtin") or not SIGNING_MODULE.exists() or SIGNING_MODULE.stat().st_size < 50:
        code = '"""NotmyFault plugin signing public keys.\nBUILTIN_PUBLIC_KEY — project maintainer\'s key, tracked in git.\nUSER_PUBLIC_KEY   — loaded from .private/signing_public.pem, not tracked.\nGenerated by build.py init-keys. DO NOT EDIT.\n"""\n'
        code += '\nimport os\nfrom typing import Optional\n\n'
        code += 'CURDIR = os.path.dirname(os.path.abspath(__file__))\n'
        code += '_PRIVATE_DIR = os.path.normpath(os.path.join(CURDIR, "..", ".private"))\n\n'
        code += f'BUILTIN_PUBLIC_KEY: bytes = {pub_bytes!r}\n\n'
        code += '_USER_PUBLIC_KEY_PATH = os.path.join(_PRIVATE_DIR, "signing_public.pem")\n\n\n'
        code += 'def _load_user_public_key() -> Optional[bytes]:\n'
        code += '    try:\n'
        code += '        with open(_USER_PUBLIC_KEY_PATH, "rb") as f:\n'
        code += '            return f.read()\n'
        code += '    except (OSError, FileNotFoundError):\n'
        code += '        return None\n\n\n'
        code += 'USER_PUBLIC_KEY: Optional[bytes] = _load_user_public_key()\n\n\n'
        code += 'def get_public_keys() -> list[bytes]:\n'
        code += '    keys: list[bytes] = []\n'
        code += '    if BUILTIN_PUBLIC_KEY:\n'
        code += '        keys.append(BUILTIN_PUBLIC_KEY)\n'
        code += '    if USER_PUBLIC_KEY:\n'
        code += '        keys.append(USER_PUBLIC_KEY)\n'
        code += '    return keys\n'
        with open(SIGNING_MODULE, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"+ 内置公钥: {SIGNING_MODULE}（检入 git）")

def cmd_sign(args):
    """签名所有插件"""
    if not PRIVATE_KEY_FILE.exists():
        print("! 私钥不存在，请先运行 build.py init-keys")
        return
    
    private_key = _load_private_key(PRIVATE_KEY_FILE)
    public_key = private_key.public_key()
    
    plugins = _collect_plugins()
    signed = 0
    for plugin_dir, json_name in plugins:
        files = _plugin_files(plugin_dir, json_name)
        payload = b""
        for f in files:
            payload += f.read_bytes()
        digest = hashlib.sha256(payload).digest()
        sig = private_key.sign(digest)
        sig_file = plugin_dir / "signature.sig"
        with open(sig_file, "wb") as f:
            f.write(sig)
        plugin_id = json.loads((plugin_dir / json_name).read_text(encoding="utf-8")).get("id", plugin_dir.name)
        print(f"  + {plugin_id:20s} signed ({len(files)} files)")
        signed += 1
    print(f"已签名 {signed} 个插件")

def cmd_verify(args):
    """验证所有插件签名"""
    ed25519, *_ = _get_crypto()
    
    try:
        from notmyfault.signing_keys import get_public_keys
        pub_keys = get_public_keys()
    except ImportError:
        print("! 无法导入公钥模块，请先运行 build.py init-keys")
        return
    
    if not pub_keys:
        print("! 没有可用的公钥，请先运行 build.py init-keys")
        return
    
    pubs = [ed25519.Ed25519PublicKey.from_public_bytes(k) for k in pub_keys]
    
    plugins = _collect_plugins()
    passed = 0
    failed = 0
    unsigned = 0
    for plugin_dir, json_name in plugins:
        sig_file = plugin_dir / "signature.sig"
        if not sig_file.exists():
            print(f"  - {plugin_dir.parent.name:10s}/{plugin_dir.name:20s} 未签名")
            unsigned += 1
            continue
        files = _plugin_files(plugin_dir, json_name)
        payload = b""
        for f in files:
            payload += f.read_bytes()
        digest = hashlib.sha256(payload).digest()
        sig = sig_file.read_bytes()
        ok = False
        for pk in pubs:
            try:
                pk.verify(sig, digest)
                ok = True
                break
            except Exception:
                continue
        if ok:
            plugin_id = json.loads((plugin_dir / json_name).read_text(encoding="utf-8")).get("id", plugin_dir.name)
            print(f"  + {plugin_id:20s} 签名有效")
            passed += 1
        else:
            print(f"  ! {plugin_dir.parent.name}/{plugin_dir.name:20s} 签名无效！")
            failed += 1
    print(f"验证完成: {passed} 有效, {failed} 无效, {unsigned} 未签名")

def cmd_build(args):
    """完整构建：签名 + build.json"""
    cmd_sign(args)
    
    # 检测分支
    branch = "unknown"
    try:
        import subprocess
        r = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True, timeout=3)
        branch = r.stdout.strip()
    except Exception:
        pass
    
    mode_map = {"master": "strict", "develop": "normal", "develop-alpha": "permissive"}
    security_mode = mode_map.get(branch, "strict")
    
    build_info = {
        "security_mode": security_mode,
        "build": branch,
        "build_time": __import__("datetime").datetime.now().isoformat(),
    }
    build_path = ROOT / "build.json"
    with open(build_path, "w", encoding="utf-8") as f:
        json.dump(build_info, f, indent=2)
    print(f"+ build.json 写入: {build_path} (mode={security_mode}, branch={branch})")

def cmd_version(args):
    """显示当前密钥状态"""
    priv_ok = PRIVATE_KEY_FILE.exists()
    try:
        from notmyfault.signing_keys import BUILTIN_PUBLIC_KEY
        pub_ok = bool(BUILTIN_PUBLIC_KEY)
    except ImportError:
        pub_ok = False
    print(f"私钥: {'✓' if priv_ok else '✗'} {PRIVATE_KEY_FILE}")
    print(f"公钥: {'✓' if pub_ok else '✗'} {SIGNING_MODULE}")
    if pub_ok:
        fp = hashlib.sha256(BUILTIN_PUBLIC_KEY).hexdigest()[:16]
        print(f"公钥指纹: {fp}...")
    plugins = _collect_plugins()
    sig_count = sum(1 for d, _ in plugins if (d / "signature.sig").exists())
    print(f"插件: {len(plugins)} 个, 已签名: {sig_count} 个")

def main():
    cmds = {
        "init-keys": cmd_init_keys,
        "sign": cmd_sign,
        "verify": cmd_verify,
        "build": cmd_build,
        "version": cmd_version,
    }
    args = {"force": "--force" in sys.argv, "builtin": "--builtin" in sys.argv, "encrypt": "--encrypt" in sys.argv}
    cmds_list = [a for a in sys.argv[1:] if not a.startswith("--")]
    
    if not cmds_list:
        print("用法: python build.py <command> [options]")
        print(f"命令: {', '.join(sorted(cmds))}")
        print("选项: --force    强制覆盖已有密钥")
        print("      --builtin  同时写入内置公钥到 signing_keys.py")
        print("      --encrypt  用密码加密私钥")
        return
    
    for cmd_name in cmds_list:
        if cmd_name in cmds:
            cmds[cmd_name](args)
        else:
            print(f"未知命令: {cmd_name}")

if __name__ == "__main__":
    main()