"""NotmyFault plugin signing public keys.
BUILTIN_PUBLIC_KEY — project maintainer's key, tracked in git.
USER_PUBLIC_KEY   — loaded from .private/signing_public.pem, not tracked.
Generated by build.py init-keys. DO NOT EDIT.
"""

import os
from typing import Optional

CURDIR = os.path.dirname(os.path.abspath(__file__))
_PRIVATE_DIR = os.path.normpath(os.path.join(CURDIR, "..", ".private"))

BUILTIN_PUBLIC_KEY: bytes = b'11\xda\xd4\xf3[\x9c\xd5\xf3e\xadF\xb16\xa4\xfe\xd1#q\xca\\\x0fsy8%PbVg\xf3H'

_USER_PUBLIC_KEY_PATH = os.path.join(_PRIVATE_DIR, "signing_public.pem")


def _load_user_public_key() -> Optional[bytes]:
    try:
        with open(_USER_PUBLIC_KEY_PATH, "rb") as f:
            return f.read()
    except (OSError, FileNotFoundError):
        return None


USER_PUBLIC_KEY: Optional[bytes] = _load_user_public_key()


def get_public_keys() -> list[bytes]:
    keys: list[bytes] = []
    if BUILTIN_PUBLIC_KEY:
        keys.append(BUILTIN_PUBLIC_KEY)
    if USER_PUBLIC_KEY:
        keys.append(USER_PUBLIC_KEY)
    return keys
